-- 중고장터: 판매자-구매자 메시지 테이블
CREATE TABLE IF NOT EXISTS community_messages (
    id bigint generated by default as identity primary key,
    from_user_id uuid not null references auth.users(id) on delete cascade,
    to_user_id uuid not null references auth.users(id) on delete cascade,
    item_id bigint,
    body text not null,
    read_at timestamptz,
    created_at timestamptz default now()
);
CREATE INDEX IF NOT EXISTS idx_community_messages_to ON community_messages(to_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_community_messages_from ON community_messages(from_user_id, created_at DESC);
ALTER TABLE community_messages ENABLE ROW LEVEL SECURITY;

-- RLS: 본인이 보낸/받은 메시지만 읽기
DROP POLICY IF EXISTS "read_own_messages" ON community_messages;
CREATE POLICY "read_own_messages" ON community_messages FOR SELECT
    USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

DROP POLICY IF EXISTS "send_own_messages" ON community_messages;
CREATE POLICY "send_own_messages" ON community_messages FOR INSERT
    WITH CHECK (auth.uid() = from_user_id);

-- 안전거래 수수료/결제수단/결제완료 컬럼 추가
ALTER TABLE community_safe_transactions
    ADD COLUMN IF NOT EXISTS fee integer default 0;
ALTER TABLE community_safe_transactions
    ADD COLUMN IF NOT EXISTS payment_method text default 'card';
ALTER TABLE community_safe_transactions
    ADD COLUMN IF NOT EXISTS paid_at timestamptz;

-- profiles.phone 컬럼 (없으면 추가)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone text;

-- 중고상품에 판매자 전화번호 캐시 컬럼 (optional)
ALTER TABLE community_secondhand ADD COLUMN IF NOT EXISTS seller_phone text;
