-- 1:1 사용자 채팅 (전문가·구매자·판매자 상담용)
CREATE TABLE IF NOT EXISTS user_chats (
    id bigint generated by default as identity primary key,
    user_a uuid not null references auth.users(id) on delete cascade,
    user_b uuid not null references auth.users(id) on delete cascade,
    topic text,                         -- '전문가 상담 #123' 등 문맥
    last_message_at timestamptz,
    created_at timestamptz default now(),
    UNIQUE (user_a, user_b, topic)
);
CREATE INDEX IF NOT EXISTS idx_user_chats_a ON user_chats(user_a, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_chats_b ON user_chats(user_b, last_message_at DESC);

CREATE TABLE IF NOT EXISTS user_chat_messages (
    id bigint generated by default as identity primary key,
    chat_id bigint not null references user_chats(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    body text not null,
    attachments jsonb,                  -- 이미지 URL 배열 등
    created_at timestamptz default now(),
    read_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_ucm_chat ON user_chat_messages(chat_id, created_at);

ALTER TABLE user_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "uc_select" ON user_chats;
CREATE POLICY "uc_select" ON user_chats FOR SELECT
    USING (auth.uid() = user_a OR auth.uid() = user_b);

DROP POLICY IF EXISTS "uc_insert" ON user_chats;
CREATE POLICY "uc_insert" ON user_chats FOR INSERT
    WITH CHECK (auth.uid() = user_a OR auth.uid() = user_b);

DROP POLICY IF EXISTS "uc_update" ON user_chats;
CREATE POLICY "uc_update" ON user_chats FOR UPDATE
    USING (auth.uid() = user_a OR auth.uid() = user_b);

DROP POLICY IF EXISTS "ucm_select" ON user_chat_messages;
CREATE POLICY "ucm_select" ON user_chat_messages FOR SELECT
    USING (EXISTS (SELECT 1 FROM user_chats c WHERE c.id = chat_id AND (auth.uid() = c.user_a OR auth.uid() = c.user_b)));

DROP POLICY IF EXISTS "ucm_insert" ON user_chat_messages;
CREATE POLICY "ucm_insert" ON user_chat_messages FOR INSERT
    WITH CHECK (auth.uid() = sender_id AND EXISTS (SELECT 1 FROM user_chats c WHERE c.id = chat_id AND (auth.uid() = c.user_a OR auth.uid() = c.user_b)));
